# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfa0bc9b0f1439317b39422b148346b6d622575074c707d887db510246169baecf8bd91b0bff613a6154df1e0ca145da8b1c103b95fb674c7ce43bdc4d4f1f80

test:
  secret_key_base: de210c2f6292972e50292a0de2f045ecfdc2dcd6f86dac923b177e91d5b926d5dc39552fb6ab238ab62e6bd4dd01dd0efc7b50bb5a1f81be63a0579b86e579cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
